version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - "mongodb"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/booksData
    ports:
      - "3000:3000"
    restart: always
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/:/data/db
    ports:
        - "27017:27017"
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - BACKEND_URI=http://localhost:3000/default
    environment:
      #  - BACKEND_URI=http://service:3000/default
      - BACKEND_URI=http://server:3000/default
    depends_on:
      - "server"
    links:
      - server
    ports:
      - "8080:80"
    restart: always

